// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKVg-JkEHvov2hs23tbbOV9Sdhgrfqop4',
    appId: '1:979441249617:web:480702628ff4ef46bfb770',
    messagingSenderId: '979441249617',
    projectId: 'test-8946a',
    authDomain: 'test-8946a.firebaseapp.com',
    storageBucket: 'test-8946a.appspot.com',
    measurementId: 'G-JVJJES4K2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXkzebR-vw2aFM-YE-SIIjw6gb7oYAl_M',
    appId: '1:979441249617:android:087acebf578ca92cbfb770',
    messagingSenderId: '979441249617',
    projectId: 'test-8946a',
    storageBucket: 'test-8946a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVYwiBOzK_Qf16SkowYRh_s3znJ6MyB4',
    appId: '1:979441249617:ios:878e73f063d805bebfb770',
    messagingSenderId: '979441249617',
    projectId: 'test-8946a',
    storageBucket: 'test-8946a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVYwiBOzK_Qf16SkowYRh_s3znJ6MyB4',
    appId: '1:979441249617:ios:878e73f063d805bebfb770',
    messagingSenderId: '979441249617',
    projectId: 'test-8946a',
    storageBucket: 'test-8946a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKVg-JkEHvov2hs23tbbOV9Sdhgrfqop4',
    appId: '1:979441249617:web:d4f3a423605a15a9bfb770',
    messagingSenderId: '979441249617',
    projectId: 'test-8946a',
    authDomain: 'test-8946a.firebaseapp.com',
    storageBucket: 'test-8946a.appspot.com',
    measurementId: 'G-73T39SXX7Z',
  );
}
